### ISSUE TITLE
Requesting CCEIP CDDIP Memory Maps in machine readable file format.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [opencomputeproject/Project-Zipline#11]
The register mapping details as provided [here](https://github.com/sifive/Project-Zipline/tree/60657e17ac9579aaf3751f0b5c0c0710946b0aa9/register_doc) are in `html` & `pdf` formats only. Can you provide the register maps in any machine readable format , like `json5`, `ip-xact` or `xml`, if possible?

**Comment by michaelgmcintyre** [comment]
Sorry Saurabhsingh,

Will be unable to provide register maps in additional formats.

**Comment by michaelgmcintyre** [comment]
Closing due to no additional activity.
