### ISSUE TITLE
Understanding the Top level parameters

### ISSUE THREAD

**Issue by Santhoshkosuna** [opencomputeproject/Project-Zipline#2]
Hi,

I came across this article and was interested in having a look at the RTL code. In the top level file, I have seen a parameter name FPGA_MODE which can be 0 or 1.
Can you please give me a brief idea of what this parameter does?

**Comment by michaelgmcintyre** [comment]
Hi Santhoshkosuna,

I was unable to locate a parameter/define for FPGA_MODE;  however, there is a define FPGA_MOD.  This define was used during development on an FPGA prototyping system.  FPGA_MOD was used to simplify
the RTL to ease the mapping to an FPGA prototyping system.  This define is not related to whether the final implementation is in an ASIC or FPGA.

Best regards

**Comment by Santhoshkosuna** [comment]
Yes, it is FPGA_MOD. 
So, Is the same functionality can be achieved for FPGA_MOD set to 0/1?

I tried to synthesize the code for FPGA boards to understand the RTL logic (FPGA_MOD set to 0). The LUT count seems to be huge. Do I need to set FPGA_MOD to 1?

Do you have any test bench which helps in understanding how the inputs to this RTL are driven? Can you please give a brief overview how the inputs needs to be driven?

**Comment by michaelgmcintyre** [comment]
FPGA_MOD was used internally during prototyping and has been deprecated.  As per the README.md, no test bench was provided during the inital release.  Please review the specifications for overview and further details.

Best regards.

**Comment by Santhoshkosuna** [comment]
I have looked at the specification document
The document says 
huf_comp_ib_in.tuser[7:0] - Multi-purpose user bits, used for signaling start and end of frames and sub-frames
Can you please specify what values needs to be set to represent start and end of frames and sub frames?

**Comment by Santhoshkosuna** [comment]
I am unable to create testbench without the knowledge of TUSER signals information. Can you please provide me some info which can help?

**Comment by Santhoshkosuna** [comment]
The information of the input signals is not clear through the spec document given. When can we expect a clear overview of the input signals so that we can use the rtl and test the functionality?
By what time we can expect a sample test bench?

**Comment by michaelgmcintyre** [comment]
Hi Santhoshkosuna,

The entire pipeline, RTL and specifications, are now posted to the respository.  Please have a look to determine if this provides the clarity you are looking for.

Best Regards
