### ISSUE TITLE
C reference implementation of X10 codec

### ISSUE THREAD

**Issue by tariqafzal** [opencomputeproject/Project-Zipline#6]
Is there a C/C++ reference implementation of X10 compressor and decompressor to benchmark some workloads.

**Comment by michaelgmcintyre** [comment]
Hi tariqafzal,

We have an internal C-based simulator that was developed early on.  It is not currently available for public distribution, but we are internal discussing if we will be releasing it.

Best regards

**Comment by sureshd-fm** [comment]
It would be so useful if you can release the reference C-code.

**Comment by michaelgmcintyre** [comment]
Hi surehd-fm,

We currently have no plans to release the c-code that we used for simulator development..  Our focus was the HW implementation, thus the RTL code.

Best regards,
Michael

**Comment by antoninomiceli** [comment]
Any plans to release a Cadence flow?

**Comment by michaelgmcintyre** [comment]
Hi Antoninomiceli,

The Zipline implementation has been produced as an ASIC.  The entire RTL used to develop that ASIC, as well as a plethora of documentation, have been released to this repository.  Since we are now in silicon there is no plan to update the RTL for this project.

Best regards,
Michael

**Comment by ghost** [comment]
Do you have plan to release the binary executable to allow running benchmarks on the compression ratio performance with various use cases?

**Comment by michaelgmcintyre** [comment]
Hi yoshihorie,

We have an internal C-based simulator that was developed early on. However, it was never intended for use outside of our organizaiton, thus it is not currently available for public distribution.  We are working to update, make more user friendly, and document.  We do not yet have a target date for when we will be making it publically available.

Best regard
