### ISSUE TITLE
Implementing the design using Vivado

### ISSUE THREAD

**Issue by siavashr** [opencomputeproject/Project-Zipline#7]
Hi,
I found this project very interesting. I wanted to run it on a Zynq board.
I tried to make this project in Xilinx Vivado, however, it seems it's not that straight forward.
Can you please give me some information about the way that I make the Vivado project?

**Comment by michaelgmcintyre** [comment]
Hi Siavashr,
Unfortunately, we are unable to support every development environment.  To my knowledge, this project has not been build with Xilinx Vivado.

**Comment by siavashr** [comment]
Thanks for your prompt response. Is there any information about the hierarchy of the RTL design? It can help me to build the design using Xilinx Vivado.

**Comment by sbates130272** [comment]
Hey @siavashr  if you get this working for Vivado I (and others) would love to see a fork or pull request for this. I suspect being able to build Zipline for FPGAs will be very popular.....

**Comment by michaelgmcintyre** [comment]
Hi Siavashr,

The entire pipeline, RTL and specifications, are now posted to the respository.  Please have a look to determine if this provides the clarity you are looking for.

Best Regards

**Comment by ANILATHOMAS519** [comment]
Hi @michaelgmcintyre ,
While trying to implement this project in Vivado, we found some syntax errors and some ports which were wrongly declared, like in file:
[ ] [https://github.com/opencomputeproject/Project-Zipline/blob/master/rtl/cr_prefix/cr_prefix_fe_ctlr.v](url)

Can you please clarify whether these are bugs or any mistakes that we are overlooking from our side?
